{
    'name': 'Medical Center Inventory',
    'version': '19.0.9.0.0',
    'category': 'Inventory',
    'summary': 'Medical inventory with vendor accounts, stock card, analytics',
    'depends': ['stock', 'mail', 'web', 'product', 'uom'],
    'data': [
        'security/ir.model.access.csv',
        'data/product_category_data.xml',
        'data/stock_location_data.xml',
        'data/ir_sequence_data.xml',
        'views/dashboard_action.xml',
        'views/stock_view_action.xml',
        'views/products_views.xml',
        'views/consumption_request_views.xml',
        'views/stock_receive_views.xml',
        'views/vendor_account_views.xml',
        'views/stock_card_views.xml',
        'views/medical_location_views.xml',
        'views/analytics_views.xml',
        'views/analytics_report_views.xml',
        'views/stock_receive_report.xml',
        'views/menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'medical_inventory/static/src/css/dashboard.css',
            'medical_inventory/static/src/css/stock_view.css',
            'medical_inventory/static/src/xml/dashboard.xml',
            'medical_inventory/static/src/xml/stock_view.xml',
            'medical_inventory/static/src/js/dashboard.js',
            'medical_inventory/static/src/js/stock_view.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'post_install_hook': 'post_install_hook',
    'post_migrate_hook': 'post_migrate_hook',
}
